import { Router } from 'express';
import { authenticate, AuthRequest } from '../middleware/auth';
import mcpManagerService from '../services/mcp/MCPManagerService';
import analyzerAgentService from '../services/mcp/AnalyzerAgentService';

const router = Router();
router.use(authenticate);

/**
 * POST /api/mcp/auto-generated
 * Create auto-generated MCP configuration
 */
router.post('/auto-generated', async (req: AuthRequest, res, next) => {
  try {
    const { apiDocumentation, name } = req.body;

    if (!apiDocumentation) {
      return res.status(400).json({
        error: {
          message: 'API documentation is required',
          code: 'MISSING_API_DOCUMENTATION',
        },
      });
    }

    // Analyze the API documentation
    const analysis = await analyzerAgentService.analyzeOpenAPI(apiDocumentation);

    // Create MCP configuration
    const config = await mcpManagerService.createAutoGeneratedMCP(
      req.user!.userId,
      apiDocumentation,
      name || 'Auto-generated MCP'
    );

    // Store generated tools in database
    for (const tool of analysis.suggestedTools) {
      await mcpManagerService.discoverTools({
        id: config.id,
        external_server_url: null,
        internal_server_url: config.internalServerUrl,
        auth_type: 'none',
        encrypted_credentials: null,
      });
    }

    res.status(201).json({
      config,
      analysis: {
        endpointsAnalyzed: analysis.endpoints.length,
        toolsGenerated: analysis.suggestedTools.length,
        dataModels: analysis.dataModels.length,
      },
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/mcp/bring-your-own
 * Create bring-your-own MCP configuration
 */
router.post('/bring-your-own', async (req: AuthRequest, res, next) => {
  try {
    const { serverUrl, authType, credentials, name } = req.body;

    if (!serverUrl) {
      return res.status(400).json({
        error: {
          message: 'Server URL is required',
          code: 'MISSING_SERVER_URL',
        },
      });
    }

    const auth = {
      type: authType || 'none',
      credentials,
    };

    const config = await mcpManagerService.createBYOMCP(
      req.user!.userId,
      serverUrl,
      auth,
      name || 'Bring-your-own MCP'
    );

    res.status(201).json(config);
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/mcp/config
 * Get user's MCP configuration
 */
router.get('/config', async (req: AuthRequest, res, next) => {
  try {
    const config = await mcpManagerService.getMCPConfig(req.user!.userId);

    if (!config) {
      return res.status(404).json({
        error: {
          message: 'No MCP configuration found',
          code: 'MCP_NOT_FOUND',
        },
      });
    }

    res.json(config);
  } catch (error) {
    next(error);
  }
});

/**
 * PUT /api/mcp/mode
 * Switch MCP mode
 */
router.put('/mode', async (req: AuthRequest, res, next) => {
  try {
    const { mode } = req.body;

    if (!mode || !['auto-generated', 'bring-your-own'].includes(mode)) {
      return res.status(400).json({
        error: {
          message: 'Valid mode is required (auto-generated or bring-your-own)',
          code: 'INVALID_MODE',
        },
      });
    }

    await mcpManagerService.switchMCPMode(req.user!.userId, mode);

    res.json({
      message: 'MCP mode switched successfully',
      newMode: mode,
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/mcp/tools
 * Get available MCP tools
 */
router.get('/tools', async (req: AuthRequest, res, next) => {
  try {
    const { role } = req.query;

    const config = await mcpManagerService.getMCPConfig(req.user!.userId);

    if (!config) {
      return res.status(404).json({
        error: {
          message: 'No MCP configuration found',
          code: 'MCP_NOT_FOUND',
        },
      });
    }

    // Get tools from database
    const { query: dbQuery } = require('../config/database');
    let tools;

    if (role) {
      tools = await dbQuery(
        `SELECT * FROM mcp_tools 
         WHERE mcp_config_id = $1 AND $2 = ANY(roles)
         ORDER BY name`,
        [config.id, role]
      );
    } else {
      tools = await dbQuery(
        `SELECT * FROM mcp_tools 
         WHERE mcp_config_id = $1
         ORDER BY name`,
        [config.id]
      );
    }

    res.json(tools.rows);
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/mcp/validate
 * Validate MCP server connection
 */
router.post('/validate', async (req: AuthRequest, res, next) => {
  try {
    const { serverUrl, authType, credentials } = req.body;

    if (!serverUrl) {
      return res.status(400).json({
        error: {
          message: 'Server URL is required',
          code: 'MISSING_SERVER_URL',
        },
      });
    }

    const auth = {
      type: authType || 'none',
      credentials,
    };

    const isValid = await mcpManagerService.validateConnection(serverUrl, auth);

    res.json({
      valid: isValid,
      serverUrl,
    });
  } catch (error) {
    next(error);
  }
});

/**
 * DELETE /api/mcp/config
 * Delete MCP configuration
 */
router.delete('/config', async (req: AuthRequest, res, next) => {
  try {
    const { query: dbQuery } = require('../config/database');
    
    await dbQuery(
      `DELETE FROM mcp_configs WHERE user_id = $1`,
      [req.user!.userId]
    );

    res.json({
      message: 'MCP configuration deleted successfully',
    });
  } catch (error) {
    next(error);
  }
});

export default router;
