-- Migration: Add MCP Configurations
-- Description: Create tables for MCP (Model Context Protocol) configurations
-- Supports both auto-generated and bring-your-own MCP modes

-- MCP Configurations table
CREATE TABLE IF NOT EXISTS mcp_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mode VARCHAR(20) NOT NULL CHECK (mode IN ('auto-generated', 'bring-your-own')),
  name VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'error')),
  
  -- Auto-generated MCP fields
  api_documentation TEXT,
  generated_tools JSONB,
  internal_server_url TEXT,
  
  -- BYO-MCP fields
  external_server_url TEXT,
  auth_type VARCHAR(20) CHECK (auth_type IN ('none', 'bearer', 'api-key')),
  encrypted_credentials TEXT,
  discovered_tools JSONB,
  
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  
  CONSTRAINT unique_user_mcp UNIQUE(user_id)
);

-- Create index for faster lookups
CREATE INDEX idx_mcp_configs_user_id ON mcp_configs(user_id);
CREATE INDEX idx_mcp_configs_status ON mcp_configs(status);

-- Add comment for documentation
COMMENT ON TABLE mcp_configs IS 'Stores MCP (Model Context Protocol) configurations for users. Supports both auto-generated and bring-your-own modes.';
COMMENT ON COLUMN mcp_configs.mode IS 'MCP mode: auto-generated (analyzer creates MCP) or bring-your-own (user provides MCP server)';
COMMENT ON COLUMN mcp_configs.api_documentation IS 'API documentation (OpenAPI, GraphQL, etc.) for auto-generated mode';
COMMENT ON COLUMN mcp_configs.generated_tools IS 'JSON array of MCP tools generated by analyzer agent';
COMMENT ON COLUMN mcp_configs.internal_server_url IS 'URL of internal MCP server for auto-generated mode';
COMMENT ON COLUMN mcp_configs.external_server_url IS 'URL of external MCP server for bring-your-own mode';
COMMENT ON COLUMN mcp_configs.encrypted_credentials IS 'Encrypted credentials for MCP server authentication';
COMMENT ON COLUMN mcp_configs.discovered_tools IS 'JSON array of tools discovered from BYO-MCP server';
